# Generated by Django 3.2.16 on 2022-12-30 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название меню')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название категории меню')),
                ('slug', models.SlugField(unique=True)),
                ('nesting_level', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('url', models.URLField(default='_', editable=False)),
                ('html_prefix', models.CharField(default='', editable=False, max_length=128)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_app.menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='menu_app.category', verbose_name='Родитель')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
