# Generated by Django 3.2.16 on 2022-12-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.SlugField(verbose_name='Название меню'),
        ),
    ]
